# Generated by Django 5.0.3 on 2024-07-17 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0004_classificationhistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClassificationHistory',
        ),
    ]
